version: "3.8"

services:
  neo4j:
    image: neo4j:2025.05.0-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    networks:
      - graphrag-net
    profiles:
      - local

  qdrant:
    image: qdrant/qdrant:v1.14.1
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - graphrag-net
    profiles:
      - local

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - graphrag-net
    profiles:
      - local

  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - NEO4J_URL=${NEO4J_URL:-neo4j://neo4j:7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - RELOAD=${RELOAD:-true}
      - WORKERS=${WORKERS:-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - .:/app
    networks:
      - graphrag-net
    command: graphrag-api

volumes:
  neo4j_data:
  qdrant_data:
  redis_data:

networks:
  graphrag-net:
    driver: bridge
